I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script
    $ nIntro(texte)
  File "game/script.rpy", line 15, in <module>
    $ nIntro(texte)
KeyError: u'province_01'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script
    $ nIntro(texte)
  File "C:\Users\chaos\OneDrive\Outils\renpy-6.99.8-sdk\renpy\ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\chaos\OneDrive\Outils\renpy-6.99.8-sdk\renpy\python.py", line 1461, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 15, in <module>
    $ nIntro(texte)
  File "C:\Users\chaos\OneDrive\Outils\renpy-6.99.8-sdk\renpy\character.py", line 819, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "C:\Users\chaos\OneDrive\Outils\renpy-6.99.8-sdk\renpy\character.py", line 801, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\chaos\OneDrive\Outils\renpy-6.99.8-sdk\renpy\substitutions.py", line 229, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'province_01'

Windows-8-6.2.9200
Ren'Py 6.99.8.959
MedWar 0.0
